[package]
name = "simple-os-rust"
version = "0.1.0"
authors = ["CallOrRet <CallOrRet@outlook.com>"]
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
spin = "0.5.2"
volatile = "0.2.6"
bootloader = { version = "0.9" }

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
